name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Java 11 Build

    steps:
    - uses: actions/checkout@v1

    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Build languages
      run: ./gradlew assembleMps

  test:
    # MPS tests seem not to work on GitHub actions
    # if: false
    runs-on: ubuntu-latest
    name: Java 11 Test

    steps:
    - uses: actions/checkout@v1

    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Install dependencies
      run: sudo apt-get install -y x11vnc xvfb

    - name: Test languages
      run: ./gradlew checkMps -Djava.awt.headless=true

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          TEST-*.xml
